# frozen_string_literal: true

source 'https://rubygems.org'

gem 'logger', '~> 1.7.0'

gem 'opentelemetry-exporter-otlp', '~> 0.31.1'
gem 'opentelemetry-sdk', '~> 1.10.0'
gem 'opentelemetry-instrumentation-all', '~> 0.89.1'
