# frozen_string_literal: true

source 'https://rubygems.org'

gem 'logger', '~> 1.7.0'

gem 'opentelemetry-exporter-otlp', '~> 0.30.0'
gem 'opentelemetry-propagator-xray', '~> 0.24.0'
gem 'opentelemetry-sdk', '~> 1.8.0'
