# frozen_string_literal: true

source 'https://rubygems.org'

gem 'logger', '~> 1.7.0'

gem 'opentelemetry-exporter-otlp', '~> 0.31.0'
gem 'opentelemetry-sdk', '~> 1.10.0'

gem 'opentelemetry-exporter-otlp-logs', '~> 0.2.0'
gem 'opentelemetry-logs-sdk', '~> 0.4.0'
