# frozen_string_literal: true

source 'https://rubygems.org'

gem 'logger', '~> 1.7.0'

gem 'opentelemetry-exporter-otlp', '~> 0.31.0'
gem 'opentelemetry-sdk', '~> 1.10.0'

gem 'opentelemetry-exporter-otlp-metrics', '~> 0.6.1'
gem 'opentelemetry-metrics-api', '~> 0.4.0'
gem 'opentelemetry-metrics-sdk', '~> 0.11.2'
