# frozen_string_literal: true

source 'https://rubygems.org'

gem 'logger', '~> 1.7.0'

gem 'opentelemetry-exporter-otlp', '~> 0.37.0'
gem 'opentelemetry-sdk', '~> 1.13.1'

gem 'opentelemetry-exporter-otlp-metrics', '~> 0.13.0'
gem 'opentelemetry-metrics-api', '~> 0.9.0'
gem 'opentelemetry-metrics-sdk', '~> 0.20.0'
